title: Adnan Bin Abdul Khaleque
author: "Adnan Bin Abdul Khaleque"
description: "Data Analyst specializing in SQL, Python, Tableau, and Excel. Transforming raw data into actionable insights for business growth and research."
url: "https://adnan-bin-abdul-khaleque.github.io/my-resume"
baseurl: ""
logo: me.png
theme: jekyll-theme-minimal
social_links:
  github: "https://github.com/adnan-bin-abdul-khaleque" 
  linkedin: "https://www.linkedin.com/in/adnan-bin-abdul-khaleque" 
  email: "adnan.abdulkhaleque@gmail.com"
markdown: kramdown
